Here I am creating a Pandas DataFrame named 'df' with 4 features and 4 observations, using random values generated by NumPy:

Task 1:

In [2]:
import numpy as np
import pandas as pd

np.random.seed(42)

data = np.random.rand(4, 4)

df = pd.DataFrame(data, columns=['Feature1', 'Feature2', 'Feature3', 'Feature4'])

We can access and manipulate the data in the DataFrame using various Pandas operations.

Task 2: Rename column names

In [3]:
df.columns = ['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']

Task 3: Descriptive statistics

In [4]:
statistics = df.describe()
print(statistics)

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.491029        0.506780        0.248122        0.654537
std          0.291252        0.386153        0.329856        0.350875
min          0.156019        0.155995        0.020584        0.183405
25%          0.319910        0.198253        0.048709        0.494845
50%          0.487828        0.460206        0.119954        0.732417
75%          0.658947        0.768733        0.319367        0.892110
max          0.832443        0.950714        0.731994        0.969910

Task 4: Check for null values and data types

In [5]:
null_counts = df.isnull().sum()
data_types = df.dtypes

print("Null Value Counts:")
print(null_counts)

print("\nData Types:")
print(data_types)

Null Value Counts:
Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

Data Types:
Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

Task 5: Display columns using location method and index location method

In [6]:
print(df.iloc[:, 1:3])
print(df[['Random value 2', 'Random value 3']])

   Random value 2  Random value 3
0        0.950714        0.731994
1        0.155995        0.058084
2        0.708073        0.020584
3        0.212339        0.181825
   Random value 2  Random value 3
0        0.950714        0.731994
1        0.155995        0.058084
2        0.708073        0.020584
3        0.212339        0.181825